name = "OutbreakDetectionCore"
uuid = "f998a708-2341-46f4-85c5-02aab2fba5ed"
version = "1.0.0-DEV"
authors = ["Callum Arnold <24391445+arnold-c@users.noreply.github.com> and contributors"]

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
LightSumTypes = "f56206fc-af4c-5561-a72a-43fe2ca5a923"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultistartOptimization = "3933049c-43be-478e-a8bb-6e0f7fd53575"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Try = "bf1d0ff0-c4a9-496b-85f0-2b0d71c4f32a"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AutoHashEquals = "2.2.0"
Bootstrap = "2.4"
Bumper = "0.7"
Chain = "1.0"
DataFrames = "1.0"
DataFramesMeta = "0.15"
Dates = "1.11.0"
Distributions = "0.25"
DrWatson = "2.19"
FLoops = "0.2"
FreqTables = "1.0"
JLD2 = "0.6"
LabelledArrays = "1.0"
LightSumTypes = "5.2.2"
LinearAlgebra = "1.0"
MultistartOptimization = "0.2.2"
NLopt = "0.6.5"
NaNMath = "1.0"
OhMyThreads = "0.8.3"
ProgressMeter = "1.0"
REPL = "1.11.0"
Random = "1.0"
Reexport = "1.0"
StaticArrays = "1.0"
Statistics = "1.0"
StatsBase = "0.34"
StructArrays = "0.7"
StyledStrings = "1.11.0"
Tables = "1.0"
Try = "0.1.1"
UnPack = "1.0"
XLSX = "0.10"
julia = "1.10"
